### PR TITLE
Make checkStorageTemplate() Work On Win &Linux

### PR DESCRIPTION
**Pull request by ais-one**
Added OS checking and commands to make it work on Windows & Linux.

The problem with Windows is that the commands can change when Windows version changes (although it is seldom), whereas Linux, the bash commands are pretty much stable.

### CODE REVIEW

**Comment by ais-one** [comment]
Hi,

I just tested it. Found a error:

Fatal error: Call to undefined method DbConfig::testConf() in C:\xampp\htdocs\wpos\installer\index.php on line 214

Just checked the DbConfig Class, indeed the funciont testConf is missing...

**Comment by ais-one** [comment]
I may need to redo the Windows commands here as well...

I just tested the file copy, it did not work. Fortunately it only affects Windows.

**Comment by micwallace** [comment]
I've fixed the testConf error, seems that function was lost during a merge from the private repo :-D

**Comment by ais-one** [comment]
that's scary, haha.

**Comment by micwallace** [comment]
Not a Git merge thankfully. I'm operating two separate repos because the hosted version includes some proprietary files that I can't make open source. I'm sure there's a better way but that's where I'm at for now! :-D

**Comment by ais-one** [comment]
No wonder. I will just download and test each time there are major updates.

**Pull request merged**
